### PR TITLE
fix permission denied

### PR DESCRIPTION
**Pull request by Tiph**
fix permission denied on folder app on the first start of the container

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Can you describe your use case ?
I use this Docker image and I never had a problem with permission

**Comment by Tiph** [comment]
- pull docker image
- follow following steps: http://jhipster.github.io/installation/

On Windows 7

**Comment by pascalgrimaud** [comment]
Ok, I got it.
It can happen when you didn't create the folder before mounting the volume.
=> can you try to create the folder before starting the container ?

For example, you launch this command without creating the **helloworld** folder:
```bash
docker run --name jhipster -w /home/jhipster/app -v ~/helloworld:/home/jhipster/app:rw -v ~/.m2:/home/jhipster/.m2:rw -p 8080:8080 -p 3000:3000 -p 3001:3001 -d -t jdubois/jhipster-docker
```

So you have the issue (root/root => app/):
```bash
$ docker exec -u jhipster -it jhipster bash
jhipster@c45738a9a1be:~/app$ cd ..
jhipster@c45738a9a1be:~$ ls -al
total 32
drwxr-xr-x 5 jhipster jhipster 4096 Feb  3 06:26 .
drwxr-xr-x 7 root     root     4096 Feb  3 06:26 ..
-rw-r--r-- 1 jhipster jhipster  220 Apr  9  2014 .bash_logout
-rw-r--r-- 1 jhipster jhipster 3637 Apr  9  2014 .bashrc
drwxr-xr-x 4 jhipster jhipster 4096 Nov 13 06:59 .m2
-rw-r--r-- 1 jhipster jhipster  675 Apr  9  2014 .profile
drwxr-xr-x 2 root     root     4096 Feb  3 06:26 app
-rw-r--r-- 1 jhipster jhipster  527 Jan 19 21:34 banner.txt
jhipster@c45738a9a1be:~$
```

If you create the folder before, it should work (jhipster/jhipster => app/)
```bash
$ mkdir helloworld
$ docker run --name jhipster -w /home/jhipster/app -v ~/helloworld:/home/jhipster/app:rw -v ~/.m2:/home/jhipster/.m2:rw -p 8080:8080 -p 3000:3000 -p 3001:3001 -d -t jdubois/jhipster-docker
ecff51277b667b7c285b651e2f21e6724b3103489fa3e233f399f35b41557778
$ docker exec -u jhipster -it ecff bash
jhipster@ecff51277b66:~/app$ cd ..
jhipster@ecff51277b66:~$ ls -al
total 32
drwxr-xr-x 5 jhipster jhipster 4096 Feb  3 06:34 .
drwxr-xr-x 7 root     root     4096 Feb  3 06:34 ..
-rw-r--r-- 1 jhipster jhipster  220 Apr  9  2014 .bash_logout
-rw-r--r-- 1 jhipster jhipster 3637 Apr  9  2014 .bashrc
drwxr-xr-x 4 jhipster jhipster 4096 Nov 13 06:59 .m2
-rw-r--r-- 1 jhipster jhipster  675 Apr  9  2014 .profile
drwxr-xr-x 2 jhipster jhipster 4096 Feb  3 06:34 app
-rw-r--r-- 1 jhipster jhipster  527 Jan 19 21:34 banner.txt
jhipster@ecff51277b66:~$
```

**Comment by Tiph** [comment]
You were right

**Pull request closed without merging**
