### PR TITLE
Use official maven3-jdk8 image as parent and reduce number of layers.

### PR DESCRIPTION
**Pull request by cthiebault**
Following Docker [best-practices](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices)

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Hello @cthiebault, different points to be discussed:

1) You proposed maven:3-jdk-8 as base image. `maven:3-jdk-8` -> `java:openjdk-8-jdk` -> `buildpack-deps:jessie-scm`. If I remember well, Julien prefered the Ubuntu base image, instead of Debian. That's why we will stay with ubuntu:trusty, and it is consistent with our [DevBox](https://github.com/jhipster/jhipster-devbox)

2) this repo will be deprecated as soon as the release of JH3.0, because we will use directly this [Dockerfile](https://github.com/jhipster/generator-jhipster/blob/master/Dockerfile) and our new organization [Jhipster](https://hub.docker.com/r/jhipster/) on Docker Hub

3) You make me thinking that we should remove the installation of maven, because we have the wrapper so these lines can be removed :
  - https://github.com/jhipster/generator-jhipster/blob/master/Dockerfile#L7-L9
  - https://github.com/jhipster/generator-jhipster/blob/master/Dockerfile#L14-L17
 
So you can review this [Dockerfile](https://github.com/jhipster/generator-jhipster/blob/master/Dockerfile) if you want and make some feedbacks!

**Comment by cthiebault** [comment]
Thanks for your feedback.

I've created a new PR https://github.com/jhipster/generator-jhipster/pull/3079 that takes in considerations your comments: it's based on Ubuntu even if I think it would be better to use the official Java 8 image as Debian & Ubuntu are very close... but I understand your position.

**Comment by pascalgrimaud** [comment]
Can this PR be closed?

**Comment by jdubois** [comment]
OK, as this repo is not deprecated!

**Pull request closed without merging**
