### PR TITLE
Add Travis CI

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Hello,

Travis CI now officially supports Docker, so I closed the other pull request and work on this.

The .travis.yml file :
* build the image from Dockerfile
* run the container from the image and mvn spring-boot:run the jhipster-sample-app
* check the logs
* try to curl

If you are interested about that, you'll have to config your https://travis-ci.org/jhipster/jhipster-docker
and use it on README.md or http://jhipster.github.io/build_status.html :
```
[![Build Status](https://travis-ci.org/jhipster/jhipster-docker.svg?branch=master)](https://travis-ci.org/jhipster/jhipster-docker)
```

### CODE REVIEW

**Comment by jdubois** [comment]
Thanks!! I'm going to try this right now with the upcoming v2.21.0 release!

**Comment by jdubois** [comment]
Argh it's not working, unfortunately:
https://travis-ci.org/jhipster/jhipster-docker

@pascalgrimaud can you have a look?

**Comment by pascalgrimaud** [comment]
Ok, I will have a look

**Comment by pascalgrimaud** [comment]
I made some tests with Travis CI.

I think the problem is from Travis CI, at the beginning, with the `sudo service docker start`
When I display `sudo iptables -L`, the "Chain DOCKER" is missing.
So, you can't start container with mapping port and the error is :
```
iptables failed: iptables --wait -t filter -A DOCKER ! -i docker0 -o docker0 -p tcp -d 172.17.0.10 --dport 8080 -j ACCEPT: iptables: No chain/target/match by that name.
```

If I restart the docker service before running container, the "Chain DOCKER" is in iptables.
So, you can start container with mapping port.

I'll make more tests to confirm that.

**Pull request merged**
