### PR TITLE
Merging exposed ports

### PR DESCRIPTION
**Pull request by lexandro**
I made a little change to merge all port exposures in one line

### CODE REVIEW

**Comment by jdubois** [comment]
Looks good, but by the way should we still use port 9000? Now with browsersync it's port 3000... Besides, does BrowserSync even work in Docker?
@lexandro did you try using BrowserSync? This is when you call "grunt serve"

**Comment by lexandro** [comment]
Nope :) I just reviewed the Dockerfile and noticed the series of EXPOSE commands. Should I replace 9000 with 3000?

**Comment by jdubois** [comment]
Probably :-)
OK, I'm going to merge your PR, and this is something I will need to check later (you're not making it worse anyway!)

**Comment by lexandro** [comment]
BTW the Dockerfile unable to build image since a month.
https://registry.hub.docker.com/u/jdubois/jhipster-docker/builds_history/5596/

**Comment by jdubois** [comment]
Thanks, I've created another ticket for this:
https://github.com/jhipster/generator-jhipster/issues/1353

**Pull request merged**
